version: "3.9"

volumes:
  data:

networks:
  app:
  database:

services:
  app:
    depends_on:
      - database
    links:
      - database:database
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      DBCONNECTION: postgresql://postgres:postgres@database:5432/postgres
      PYTHONPATH: /src
    volumes:
      - ./src:/src
    ports:
      - 8080:8080
    container_name: olhadinha_back_end
    command: sh -c "python app.py -B -m flask --app app run --debug"
    networks:
      - app
      - database

  database:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: public
    ports:
      - 5432:5433
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - database