version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DBCONNECTION=''
    volumes:
      - ./src:/src
    ports:
      - 8080:8080
    container_name: olhadinha_back_end
    command: sh -c "python app.py -B -m flask --app app run --debug" 