FROM node:20-alpine as build

RUN mkdir /app
WORKDIR /app
COPY frontend/package.json .
RUN npm install
ENV VITE_CONNECTION_BACK http://localhost:8080/
COPY frontend/ .

RUN npm run build

FROM nginx:1.25.2-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx/default.prod.conf /etc/nginx/conf.d/default.conf