version: "3.9"

volumes:
  data:
  node_modules:

networks:
  backend_app:
  database:

services:
  nginx:
    depends_on:
      - backend_app
    restart: always
    build: 
      context: ./nginx
    networks:
      - backend_app

  backend_app:
    build: 
      context: ./backend

  database:
    image: postgres:15.3