version: "3.9"

volumes:
  data:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      DBCONNECTION: postgresql://postgres:postgres@192.168.0.102:5433/public
      PYTHONPATH: /src
    volumes:
      - ./src:/src
    ports:
      - 8080:8080
    container_name: olhadinha_back_end
    command: sh -c "python app.py -B -m flask --app app run --debug"

  database:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: public
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data