FROM node:20-alpine as build

RUN mkdir /app
WORKDIR /app
COPY frontend/package.json .
RUN npm install
ENV VITE_CONNECTION_BACK http://15.229.11.35:8080/api
ENV VITE_VALUE_CONFIRMATION_BACK Olhadinha12#45CfmFrnBck
ENV VITE_PASSWORD_CONFIRMATION_BACK olhadinhaFrnt3212#4@5
COPY frontend/ .

RUN npm run build

FROM nginx:1.25.2-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx/default.prod.conf /etc/nginx/conf.d/default.conf