name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Run Containers
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
      - name: Setup Database
        run: docker exec back_olhadinha_dev cd bin/setupDataBase.sh

      # aqui eu preciso setar toda uma configuração para o banco de dados quando ele subir basicamente:
      # configurar tabelas e seeaders, fazer isso no backend por que vai tambem certir como automação 
      # para subir mais rapido o banco

      # Automatizar essa tarefa com shell script.

      - name: BackEnd Test
        run: docker exec back_olhadinha_dev python -m pytest
      - name: FrontEnd Tests
        run: docker exec front_olhadinha_dev npm run test