name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Run Containers
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
      # - name: Setup Database
      #   run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml exec backend_app sh -c 'bin/setupDatabase.sh'
      - name: tmp directory
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml exec backend_app mkdir -p /tmp/setup
      - name: copy directory
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml cp ./bin/setupDatabase.sh backend_app:/tmp/setup/
      - name: exec setup DB
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml exec backend_app sh -c '/tmp/setup/setupDatabase.sh'

      - name: BackEnd Test
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml exec backend_app sh -c 'python -m pytest'
      - name: FrontEnd Tests
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml exec frontend_app sh -c 'bin/setupDatabase.sh'