name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Run Containers
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
      # - name: Giving permission to file
      #   run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml exec backend_app bash -c "chmod +x bin/setupDatabase.sh"
      - name: Setup Database
        # run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml exec backend_app bash -c 'bin/setupDatabase.sh'
        run: docker exec back_olhadinha_dev bash -c 'bin/setupDatabase.sh'
      - name: BackEnd Test
        run: docker exec back_olhadinha_dev python -m pytest
        # run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml exec backend_app bash -c 'python -m pytest'
      - name: FrontEnd Tests
        run: docker exec front_olhadinha_dev npm run test
        # run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml exec frontend_app bash -c 'bin/setupDatabase.sh'