name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Run Containers
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
      - name: Setup Database
        run: docker exec back_olhadinha_dev bash -c 'bin/setupDatabase.sh'
      - name: BackEnd Test
        run: docker exec back_olhadinha_dev python -m pytest
      - name: FrontEnd Tests
        run: docker exec front_olhadinha_dev npm run test
  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: Run commands on EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PEM }}
        run: |
          echo $PRIVATE_KEY > GIOVANNY.pem
          chmod 600 GIOVANNY.pem
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          ssh-keyscan -H ec2-15-229-11-35.sa-east-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          ssh -i "GIOVANNY.pem" ubuntu@ec2-15-229-11-35.sa-east-1.compute.amazonaws.com ls