name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Run Containers
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
      - name: Setup Database
        run: docker exec back_olhadinha_dev bash -c 'bin/setupDatabase.sh'
      - name: BackEnd Test
        run: docker exec back_olhadinha_dev python -m pytest
      - name: FrontEnd Tests
        run: docker exec front_olhadinha_dev npm run test
  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SCRIPT_AFTER: |
            docker rm -f $(docker ps -aq)
            docker rmi olhadinha-nginx
            docker rmi olhadinha-backend_app
            cd bin && ./applicationEnvironment.sh prod up